#!/bin/bash

echo "HBar Menu:"
python2 $( dirname $( readlink -f $0 ) )/hbar_retriever.py

echo "Fuel Menu:"
python2 $( dirname $( readlink -f $0 ) )/fuel_retriever.py

echo "SCR Menu:"
python2 $( dirname $( readlink -f $0 ) )/scr_retriever.py
